/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learnMgt.view.main.Dialogs;

import com.formdev.flatlaf.FlatLightLaf;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import learnMgt.model.Users;
import learnMgt.service.UsersService;
import learnMgt.view.main.AdministratorMain;
import learnMgt.view.main.InstructorMain;
import learnMgt.view.main.LearnerMain;

/**
 *
 * @author ELOHOME LTD
 */
public class Login extends javax.swing.JDialog {

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static Timestamp updateLoginDate() {
        // Get the current system time in milliseconds
        long currentTimeMillis = System.currentTimeMillis();

        // Create a new Date object representing the current time
        Date currentDate = new Date(currentTimeMillis);

        // Convert the Date object to a Timestamp object
        return new Timestamp(currentDate.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        forgotPassword = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        usernameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Username or Email"));

        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        passwordTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(178, 178, 178));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome Again! Login HERE!");

        forgotPassword.setText("Forgot Password");
        forgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordActionPerformed(evt);
            }
        });

        jLabel2.setText("- OR -");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTxt)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(loginBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(forgotPassword)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(forgotPassword)
                    .addComponent(jLabel2))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String enteredIdentifier = usernameTxt.getText();
        String enteredPassword = passwordTxt.getText();

        try {
            Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
            UsersService userService = (UsersService) registry.lookup("user");

            Users user = new Users();
            user.getUserid();
            Users userById = userService.searchUsers(user);

            
                if (userById.getUsername().equals(enteredIdentifier) && userById.getPassword().equals(enteredPassword)) {
                    // Username and password are correct
                    String userRole = userById.getRole();
                    Timestamp loginDate = updateLoginDate();
                    userById.setLoginDate(loginDate);

                    // Determine which page to bring based on the user's role
                    if ("Administration".equals(userRole)) {
                        // Open the Administrator's page
                        AdministratorMain admin = new AdministratorMain();
                        admin.setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(this, "Welcome, Administrator!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else if ("Instructor".equals(userRole)) {
                        // Open the Instructor's page
                        InstructorMain instructor = new InstructorMain();
                        instructor.setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(this, "Welcome, Instructor!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else if ("Learner".equals(userRole)) {
                        // Open the Learner's page
                        LearnerMain learner = new LearnerMain();
                        learner.setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(this, "Welcome, Learner!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } 
                } else {
                    // Username or password is incorrect
                    JOptionPane.showMessageDialog(this, "Incorrect username or password", "Error", JOptionPane.ERROR_MESSAGE);
                }
             
        } catch (Exception e) {
            e.printStackTrace();
            // Handle exceptions
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void forgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordActionPerformed
        // TODO add your handling code here:
        forgotPassword pass = new forgotPassword(null, true);
        pass.setVisible(true);
    }//GEN-LAST:event_forgotPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatLightLaf.setup();
        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton forgotPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
