/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learnMgt.view.main;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Component;
import javaswingdev.menu.EventMenuSelected;
import learnMgt.view.forms.LearnForms.LearnAssessmentsForm;
import learnMgt.view.forms.LearnForms.LearnDashboardForm;
import learnMgt.view.forms.LearnForms.LearnGradeBookForm;
import learnMgt.view.forms.LearnForms.LearnInterractForm;
import learnMgt.view.forms.LearnForms.LearnProfile;
import learnMgt.view.forms.LearnForms.LearnerClassesForm;
import learnMgt.view.forms.LearnForms.LearnerCoursesForm;

/**
 *
 * @author ELOHOME LTD
 */
public class LearnerMain extends javax.swing.JFrame {

    private static LearnerMain main;
    /**
     * Creates new form LearnerMain
     */
    public LearnerMain() {
        initComponents();
        init();
    }

    private void init() {
        main = this;
        try {

            menu.addEvent(new EventMenuSelected() {
                @Override
                public void menuSelected(int index, int indexSubMenu) {
                     if (index == 0 && indexSubMenu == 0) {
                        showForm(new LearnDashboardForm());
                    } else if (index == 1 && indexSubMenu == 0) {
                        showForm(new LearnProfile());
                    } else if (index == 2 && indexSubMenu == 1) {
                        showForm(new LearnerCoursesForm());
                    }else if (index == 2 && indexSubMenu == 2) {
                        showForm(new LearnerClassesForm());
                    }else if (index == 2 && indexSubMenu == 3) {
                        showForm(new LearnAssessmentsForm());
                    }
                    else if (index == 3 && indexSubMenu == 0) {
                        showForm(new LearnInterractForm());
                    }else if (index == 4 && indexSubMenu == 0) {
                        showForm(new LearnGradeBookForm());
                    }
                }
            });
            menu.setSelectedIndex(0, 0);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    public void showForm(Component com) {
        body.removeAll();
        body.add(com);
        body.repaint();
        body.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        menu = new learnMgt.view.menu.LearnerMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(210);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(271, 541));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        body.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(body);

        jSplitPane1.setRightComponent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
            FlatMacLightLaf.setup();
        } catch (Exception e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private learnMgt.view.menu.LearnerMenu menu;
    // End of variables declaration//GEN-END:variables
}
