/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package learnMgt.view.forms.InstruForms.dialogs;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import learnMgt.model.Assessment;
import learnMgt.service.AssessmentService;
import learnMgt.service.QuestionService;

/**
 *
 * @author ELOHOME LTD
 */
public class addAssessment extends javax.swing.JDialog {

    /**
     * Creates new form addAssessment
     */
    public addAssessment(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addQuestBtn = new javax.swing.JButton();
        saveAssessmentBtn = new javax.swing.JButton();
        assessTitleTxt = new javax.swing.JTextField();
        viewAllQuery = new javax.swing.JButton();
        courseTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Assessment");

        addQuestBtn.setText("Add Questions");
        addQuestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQuestBtnActionPerformed(evt);
            }
        });

        saveAssessmentBtn.setText("Save Assignment");
        saveAssessmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAssessmentBtnActionPerformed(evt);
            }
        });

        assessTitleTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Assessment Title"));

        viewAllQuery.setText("View all Questions");
        viewAllQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllQueryActionPerformed(evt);
            }
        });

        courseTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Course Title"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(addQuestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(viewAllQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(saveAssessmentBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(courseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(assessTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addQuestBtn)
                    .addComponent(viewAllQuery))
                .addGap(57, 57, 57)
                .addComponent(assessTitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(saveAssessmentBtn)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addQuestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQuestBtnActionPerformed
        // TODO add your handling code here:
        AddQuestions query = new AddQuestions(null, true);
        query.setVisible(true);
    }//GEN-LAST:event_addQuestBtnActionPerformed

    private void saveAssessmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAssessmentBtnActionPerformed
        // TODO add your handling code here:
        Assessment numb = new Assessment();
        courseTxt.setText(numb.getCourse().getTitle());
        String Atitle = assessTitleTxt.getText();
        //String courseName = courseTxt.setText(numb.getCourse().getTitle());

        try {
            if (Atitle.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Registry registry = LocateRegistry.getRegistry("127.0.0.1", 5000);
                AssessmentService courseService = (AssessmentService) registry.lookup("courses");
                Assessment qts = new Assessment();
                qts.setTitle(Atitle);
                qts.getCourse().getTitle();

                //course.getInstructor().getUser().getFirstName();
//                course.getInstructor().getUser().getDepartments().getName();
                Assessment registeredQuestion = courseService.saveAssessment(qts);
                if (registeredQuestion != null) {
                    // If registration is successful, close the current window and display a success message
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Question registered successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // If registration fails, display an appropriate error message
                    JOptionPane.showMessageDialog(this, "Failed to register course. Please try again later.", "Registration Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_saveAssessmentBtnActionPerformed

    private void viewAllQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllQueryActionPerformed
        // TODO add your handling code here:
        ViewQurys qts=new ViewQurys(null, true);
        qts.setVisible(true);
    }//GEN-LAST:event_viewAllQueryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatMacLightLaf.setup();
        } catch (Exception e) {
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addAssessment dialog = new addAssessment(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQuestBtn;
    private javax.swing.JTextField assessTitleTxt;
    private javax.swing.JTextField courseTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveAssessmentBtn;
    private javax.swing.JButton viewAllQuery;
    // End of variables declaration//GEN-END:variables
}
